// apps/mobile/src/components/LinkPreviewCard.tsx
import type { LinkPreviewMetadata } from "@vex-chat/store";

import React from "react";
import { Image, Pressable, StyleSheet, Text, View } from "react-native";

import { Ionicons } from "@expo/vector-icons";

import { openExternalUrl } from "../lib/externalLinks";
import { loadLinkPreviewForContent } from "../lib/linkPreview";
import { colors, typography } from "../theme";

export function LinkPreviewCard({ content }: { content: string }) {
    const [imageFailed, setImageFailed] = React.useState(false);
    const [preview, setPreview] = React.useState<LinkPreviewMetadata | null>(
        null,
    );

    React.useEffect(() => {
        let cancelled = false;
        setPreview(null);
        setImageFailed(false);

        void loadLinkPreviewForContent(content).then((nextPreview) => {
            if (!cancelled) {
                setPreview(nextPreview);
            }
        });

        return () => {
            cancelled = true;
        };
    }, [content]);

    if (!preview) {
        return null;
    }

    const displayUrl = displayUrlForPreview(preview.url);
    const hasImage = preview.imageUrl && !imageFailed;

    return (
        <Pressable
            accessibilityRole="link"
            onPress={() => {
                openExternalUrl(preview.url);
            }}
            style={({ pressed }) => [
                styles.card,
                pressed ? styles.cardPressed : null,
            ]}
        >
            {hasImage ? (
                <Image
                    onError={() => {
                        setImageFailed(true);
                    }}
                    resizeMode="cover"
                    source={{ uri: preview.imageUrl }}
                    style={styles.image}
                />
            ) : null}
            <View style={styles.copy}>
                <View style={styles.sourceRow}>
                    {preview.faviconUrl ? (
                        <Image
                            source={{ uri: preview.faviconUrl }}
                            style={styles.favicon}
                        />
                    ) : (
                        <Ionicons
                            color={colors.muted}
                            name="link-outline"
                            size={13}
                        />
                    )}
                    <Text numberOfLines={1} style={styles.source}>
                        {preview.siteName || displayUrl}
                    </Text>
                </View>
                <Text numberOfLines={2} style={styles.title}>
                    {preview.title}
                </Text>
                {preview.description ? (
                    <Text numberOfLines={2} style={styles.description}>
                        {preview.description}
                    </Text>
                ) : null}
                <Text numberOfLines={1} style={styles.url}>
                    {displayUrl}
                </Text>
            </View>
        </Pressable>
    );
}

function displayUrlForPreview(url: string): string {
    try {
        const parsed = new URL(url);
        return `${parsed.hostname.replace(/^www\./i, "")}${parsed.pathname}`;
    } catch {
        return url;
    }
}

const styles = StyleSheet.create({
    card: {
        backgroundColor: "rgba(255,255,255,0.045)",
        borderColor: "rgba(255,255,255,0.1)",
        borderRadius: 8,
        borderWidth: 1,
        marginTop: 6,
        maxWidth: 360,
        overflow: "hidden",
    },
    cardPressed: {
        opacity: 0.84,
    },
    copy: {
        gap: 4,
        padding: 10,
    },
    description: {
        ...typography.body,
        color: colors.muted,
        fontSize: 12,
        lineHeight: 17,
    },
    favicon: {
        borderRadius: 2,
        height: 13,
        width: 13,
    },
    image: {
        backgroundColor: colors.input,
        height: 150,
        width: "100%",
    },
    source: {
        ...typography.body,
        color: colors.muted,
        flex: 1,
        fontSize: 11,
        fontWeight: "600",
    },
    sourceRow: {
        alignItems: "center",
        flexDirection: "row",
        gap: 6,
    },
    title: {
        ...typography.button,
        color: colors.textSecondary,
        fontSize: 14,
    },
    url: {
        ...typography.body,
        color: colors.info,
        fontSize: 11,
    },
});

// apps/desktop/src/lib/LinkPreviewCard.svelte
<script lang="ts">
    import type { LinkPreviewMetadata } from "@vex-chat/store";

    import { extractLinkPreviewUrl } from "@vex-chat/store";

    import { openExternalUrl } from "./externalLinks.js";
    import { loadLinkPreviewForContent } from "./linkPreview.js";

    let { content }: { content: string } = $props();
    let sentinelEl: HTMLSpanElement | null = $state(null);
    let preview: LinkPreviewMetadata | null = $state(null);
    let imageFailed = $state(false);
    let shouldLoad = $state(false);

    $effect(() => {
        const previewUrl = extractLinkPreviewUrl(content);
        shouldLoad = false;
        preview = null;
        imageFailed = false;

        if (!previewUrl) {
            return;
        }
        if (typeof IntersectionObserver === "undefined") {
            shouldLoad = true;
            return;
        }
        if (!sentinelEl) {
            return;
        }

        const observer = new IntersectionObserver(
            (entries) => {
                if (entries.some((entry) => entry.isIntersecting)) {
                    shouldLoad = true;
                    observer.disconnect();
                }
            },
            { rootMargin: "320px 0px" },
        );
        observer.observe(sentinelEl);

        return () => {
            observer.disconnect();
        };
    });

    $effect(() => {
        if (!shouldLoad) {
            return;
        }
        let cancelled = false;

        void loadLinkPreviewForContent(content).then((nextPreview) => {
            if (!cancelled) {
                preview = nextPreview;
            }
        });

        return () => {
            cancelled = true;
        };
    });

    function displayUrl(url: string): string {
        try {
            const parsed = new URL(url);
            return `${parsed.hostname.replace(/^www\./i, "")}${parsed.pathname}`;
        } catch {
            return url;
        }
    }

    function openPreview(): void {
        if (preview) {
            openExternalUrl(preview.url);
        }
    }
</script>

{#if preview}
    <button class="link-preview" type="button" onclick={openPreview}>
        {#if preview.imageUrl && !imageFailed}
            <img
                class="link-preview__image"
                src={preview.imageUrl}
                alt=""
                onerror={() => {
                    imageFailed = true;
                }}
            />
        {/if}
        <span class="link-preview__body">
            <span class="link-preview__source">
                {#if preview.faviconUrl}
                    <img
                        class="link-preview__favicon"
                        src={preview.faviconUrl}
                        alt=""
                    />
                {/if}
                <span class="link-preview__site">
                    {preview.siteName || displayUrl(preview.url)}
                </span>
            </span>
            <span class="link-preview__title">{preview.title}</span>
            {#if preview.description}
                <span class="link-preview__description">
                    {preview.description}
                </span>
            {/if}
            <span class="link-preview__url">{displayUrl(preview.url)}</span>
        </span>
    </button>
{:else}
    <span class="link-preview-sentinel" bind:this={sentinelEl}></span>
{/if}

<style>
    .link-preview-sentinel {
        display: block;
        height: 1px;
        width: 1px;
    }

    .link-preview {
        display: block;
        width: min(420px, 100%);
        overflow: hidden;
        margin: 6px 0 2px;
        padding: 0;
        text-align: left;
        background: var(--bg-surface);
        border: 1px solid var(--border);
        border-radius: var(--radius-md);
        color: inherit;
        cursor: pointer;
        transition:
            background 140ms var(--ease-out),
            border-color 140ms var(--ease-out);
    }

    .link-preview:hover {
        background: var(--bg-hover);
        border-color: var(--border-strong);
    }

    .link-preview__body {
        display: flex;
        flex-direction: column;
        gap: 4px;
        padding: 10px 12px;
    }

    .link-preview__description {
        display: -webkit-box;
        overflow: hidden;
        color: var(--text-muted);
        font-size: 12px;
        line-height: 1.45;
        -webkit-box-orient: vertical;
        -webkit-line-clamp: 2;
        line-clamp: 2;
    }

    .link-preview__favicon {
        width: 14px;
        height: 14px;
        border-radius: 2px;
    }

    .link-preview__image {
        display: block;
        width: 100%;
        height: 150px;
        object-fit: cover;
        background: var(--bg-tertiary);
    }

    .link-preview__site {
        overflow: hidden;
        color: var(--text-muted);
        font-size: 11px;
        font-weight: 600;
        text-overflow: ellipsis;
        white-space: nowrap;
    }

    .link-preview__source {
        display: flex;
        align-items: center;
        min-width: 0;
        gap: 6px;
    }

    .link-preview__title {
        display: -webkit-box;
        overflow: hidden;
        color: var(--text-primary);
        font-size: 14px;
        font-weight: 650;
        line-height: 1.35;
        -webkit-box-orient: vertical;
        -webkit-line-clamp: 2;
        line-clamp: 2;
    }

    .link-preview__url {
        overflow: hidden;
        color: var(--accent-text);
        font-family: var(--font-mono);
        font-size: 10.5px;
        letter-spacing: 0.02em;
        text-overflow: ellipsis;
        white-space: nowrap;
    }
</style>
