// apps/desktop/src/lib/LinkPreviewCard.svelte
<script lang="ts">
    import type { LinkPreviewMetadata } from "@vex-chat/store";

    import { extractLinkPreviewUrl } from "@vex-chat/store";

    import { openUrl } from "@tauri-apps/plugin-opener";

    import { loadLinkPreviewForContent } from "./linkPreview.js";

    let { content }: { content: string } = $props();
    let sentinelEl: HTMLSpanElement | null = $state(null);
    let preview: LinkPreviewMetadata | null = $state(null);
    let imageFailed = $state(false);
    let shouldLoad = $state(false);

    $effect(() => {
        const previewUrl = extractLinkPreviewUrl(content);
        shouldLoad = false;
        preview = null;
        imageFailed = false;

        if (!previewUrl) {
            return;
        }
        if (typeof IntersectionObserver === "undefined") {
            shouldLoad = true;
            return;
        }
        if (!sentinelEl) {
            return;
        }

        const observer = new IntersectionObserver(
            (entries) => {
                if (entries.some((entry) => entry.isIntersecting)) {
                    shouldLoad = true;
                    observer.disconnect();
                }
            },
            { rootMargin: "320px 0px" },
        );
        observer.observe(sentinelEl);

        return () => {
            observer.disconnect();
        };
    });

    $effect(() => {
        if (!shouldLoad) {
            return;
        }
        let cancelled = false;

        void loadLinkPreviewForContent(content).then((nextPreview) => {
            if (!cancelled) {
                preview = nextPreview;
            }
        });

        return () => {
            cancelled = true;
        };
    });

    function displayUrl(url: string): string {
        try {
            const parsed = new URL(url);
            return `${parsed.hostname.replace(/^www\./i, "")}${parsed.pathname}`;
        } catch {
            return url;
        }
    }

    function openPreview(): void {
        if (preview) {
            openUrl(preview.url).catch(console.error);
        }
    }
</script>

{#if preview}
    <button class="link-preview" type="button" onclick={openPreview}>
        {#if preview.imageUrl && !imageFailed}
            <img
                class="link-preview__image"
                src={preview.imageUrl}
                alt=""
                onerror={() => {
                    imageFailed = true;
                }}
            />
        {/if}
        <span class="link-preview__body">
            <span class="link-preview__source">
                {#if preview.faviconUrl}
                    <img
                        class="link-preview__favicon"
                        src={preview.faviconUrl}
                        alt=""
                    />
                {/if}
                <span class="link-preview__site">
                    {preview.siteName || displayUrl(preview.url)}
                </span>
            </span>
            <span class="link-preview__title">{preview.title}</span>
            {#if preview.description}
                <span class="link-preview__description">
                    {preview.description}
                </span>
            {/if}
            <span class="link-preview__url">{displayUrl(preview.url)}</span>
        </span>
    </button>
{:else}
    <span class="link-preview-sentinel" bind:this={sentinelEl}></span>
{/if}

<style>
    .link-preview-sentinel {
        display: block;
        height: 1px;
        width: 1px;
    }

    .link-preview {
        display: block;
        width: min(420px, 100%);
        overflow: hidden;
        margin: 6px 0 2px;
        padding: 0;
        text-align: left;
        background: var(--bg-surface);
        border: 1px solid var(--border);
        border-radius: 8px;
        color: inherit;
        cursor: pointer;
    }

    .link-preview:hover {
        background: var(--bg-hover);
    }

    .link-preview__body {
        display: flex;
        flex-direction: column;
        gap: 4px;
        padding: 10px 12px;
    }

    .link-preview__description {
        display: -webkit-box;
        overflow: hidden;
        color: var(--text-muted);
        font-size: 12px;
        line-height: 1.45;
        -webkit-box-orient: vertical;
        -webkit-line-clamp: 2;
        line-clamp: 2;
    }

    .link-preview__favicon {
        width: 14px;
        height: 14px;
        border-radius: 2px;
    }

    .link-preview__image {
        display: block;
        width: 100%;
        height: 150px;
        object-fit: cover;
        background: var(--bg-tertiary);
    }

    .link-preview__site {
        overflow: hidden;
        color: var(--text-muted);
        font-size: 11px;
        font-weight: 600;
        text-overflow: ellipsis;
        white-space: nowrap;
    }

    .link-preview__source {
        display: flex;
        align-items: center;
        min-width: 0;
        gap: 6px;
    }

    .link-preview__title {
        display: -webkit-box;
        overflow: hidden;
        color: var(--text-primary);
        font-size: 14px;
        font-weight: 650;
        line-height: 1.35;
        -webkit-box-orient: vertical;
        -webkit-line-clamp: 2;
        line-clamp: 2;
    }

    .link-preview__url {
        overflow: hidden;
        color: var(--accent);
        font-size: 11px;
        text-overflow: ellipsis;
        white-space: nowrap;
    }
</style>

// apps/website/src/app/components/LinkPreviewCard.tsx
import type { LinkPreviewMetadata } from "@vex-chat/store";

import { ExternalLink } from "lucide-preact";
import { useEffect, useRef, useState } from "preact/hooks";

import { extractLinkPreviewUrl } from "@vex-chat/store";

import { loadLinkPreviewForContent } from "../lib/linkPreview";

export function LinkPreviewCard({ content }: { content: string }) {
    const sentinelRef = useRef<HTMLSpanElement | null>(null);
    const [preview, setPreview] = useState<LinkPreviewMetadata | null>(null);
    const [imageFailed, setImageFailed] = useState(false);
    const [faviconFailed, setFaviconFailed] = useState(false);
    const [shouldLoad, setShouldLoad] = useState(false);

    useEffect(() => {
        setPreview(null);
        setImageFailed(false);
        setFaviconFailed(false);
        setShouldLoad(false);
        if (!extractLinkPreviewUrl(content)) return;
        if (typeof IntersectionObserver === "undefined") {
            setShouldLoad(true);
            return;
        }
        const sentinel = sentinelRef.current;
        if (!sentinel) return;
        const observer = new IntersectionObserver(
            (entries) => {
                if (!entries.some((entry) => entry.isIntersecting)) return;
                setShouldLoad(true);
                observer.disconnect();
            },
            { rootMargin: "320px 0px" },
        );
        observer.observe(sentinel);
        return () => observer.disconnect();
    }, [content]);

    useEffect(() => {
        if (!shouldLoad) return;
        let active = true;
        void loadLinkPreviewForContent(content).then((next) => {
            if (active) setPreview(next);
        });
        return () => {
            active = false;
        };
    }, [content, shouldLoad]);

    if (!preview) {
        return <span className="link-preview-sentinel" ref={sentinelRef} />;
    }

    return (
        <a
            aria-label={`Open ${preview.title}`}
            className="link-preview"
            href={preview.url}
            rel="noreferrer noopener"
            target="_blank"
        >
            {preview.imageUrl && !imageFailed ? (
                <img
                    alt=""
                    className="link-preview__image"
                    loading="lazy"
                    referrerPolicy="no-referrer"
                    src={preview.imageUrl}
                    onError={() => setImageFailed(true)}
                />
            ) : null}
            <span className="link-preview__body">
                <span className="link-preview__source">
                    {preview.faviconUrl && !faviconFailed ? (
                        <img
                            alt=""
                            className="link-preview__favicon"
                            loading="lazy"
                            referrerPolicy="no-referrer"
                            src={preview.faviconUrl}
                            onError={() => setFaviconFailed(true)}
                        />
                    ) : null}
                    <span className="link-preview__site">
                        {preview.siteName || displayURL(preview.url)}
                    </span>
                </span>
                <span className="link-preview__title">{preview.title}</span>
                {preview.description ? (
                    <span className="link-preview__description">
                        {preview.description}
                    </span>
                ) : null}
                <span className="link-preview__url">
                    <span>{displayURL(preview.url)}</span>
                    <ExternalLink size={12} />
                </span>
            </span>
        </a>
    );
}

function displayURL(value: string): string {
    try {
        const url = new URL(value);
        const path = url.pathname === "/" ? "" : url.pathname;
        return `${url.hostname.replace(/^www\./iu, "")}${path}`;
    } catch {
        return value;
    }
}
