// apps/desktop/src/lib/PasskeyUpgradePrompt.svelte
<script lang="ts">
    import { push } from "svelte-spa-router";

    import { KeyRound, X } from "@lucide/svelte";

    import { passkeyUpgradePrompt, vexService } from "./store/index.js";

    const SETUP_INTENT_KEY = "vex-passkey-setup-intent";
    let closeButtonElement: HTMLButtonElement | null = $state(null);
    let primaryButtonElement: HTMLButtonElement | null = $state(null);

    function focusOnMount(node: HTMLButtonElement): { destroy(): void } {
        const previousFocus = document.activeElement;
        const frame = requestAnimationFrame(() => {
            node.focus();
        });
        return {
            destroy(): void {
                cancelAnimationFrame(frame);
                if (previousFocus instanceof HTMLElement) {
                    previousFocus.focus();
                }
            },
        };
    }

    function dismiss(): void {
        vexService.dismissPasskeyUpgradePrompt();
    }

    function startSetup(): void {
        const prompt = $passkeyUpgradePrompt;
        if (!prompt) return;
        sessionStorage.setItem(
            SETUP_INTENT_KEY,
            JSON.stringify({
                reason: prompt.reason,
                suggestedName: passkeyNameForDevice(prompt.deviceName),
            }),
        );
        dismiss();
        void push("/settings/passkeys");
    }

    function handleKeydown(event: KeyboardEvent): void {
        if (!$passkeyUpgradePrompt) return;
        if (event.key === "Escape") {
            dismiss();
            return;
        }
        if (
            event.key !== "Tab" ||
            !closeButtonElement ||
            !primaryButtonElement
        ) {
            return;
        }
        if (event.shiftKey && document.activeElement === closeButtonElement) {
            event.preventDefault();
            primaryButtonElement.focus();
        } else if (
            !event.shiftKey &&
            document.activeElement === primaryButtonElement
        ) {
            event.preventDefault();
            closeButtonElement.focus();
        }
    }

    function deviceLabelForPrompt(deviceName: string): string {
        const normalized = deviceName.trim().toLowerCase();
        if (normalized.startsWith("mac")) return "this Mac";
        if (normalized.startsWith("win")) return "this Windows PC";
        if (normalized.includes("linux")) return "this Linux computer";
        return deviceName.trim() || "this device";
    }

    function passkeyNameForDevice(deviceName: string): string {
        const normalized = deviceName.trim().toLowerCase();
        if (normalized.startsWith("mac")) return "Mac";
        if (normalized.startsWith("win")) return "Windows PC";
        if (normalized.includes("linux")) return "Linux computer";
        return deviceName.trim() || "This device";
    }
</script>

<svelte:window onkeydown={handleKeydown} />

{#if $passkeyUpgradePrompt}
    {@const fromAnotherAuthenticator =
        $passkeyUpgradePrompt.reason === "cross_platform_passkey"}
    <div class="passkey-prompt">
        <button
            class="passkey-prompt__backdrop"
            type="button"
            aria-label="Dismiss passkey suggestion"
            onclick={dismiss}
        ></button>
        <div
            class="passkey-prompt__dialog"
            role="dialog"
            aria-labelledby="passkey-prompt-title"
            aria-modal="true"
        >
            <button
                bind:this={closeButtonElement}
                class="passkey-prompt__close"
                type="button"
                aria-label="Not now"
                title="Not now"
                onclick={dismiss}
            >
                <X size={18} />
            </button>
            <span class="passkey-prompt__icon"><KeyRound size={24} /></span>
            <div class="passkey-prompt__copy">
                <span class="passkey-prompt__eyebrow">Faster sign-in</span>
                <h2 id="passkey-prompt-title">
                    {fromAnotherAuthenticator
                        ? "Add a passkey to this device"
                        : "Skip your password next time"}
                </h2>
                <p>
                    {fromAnotherAuthenticator
                        ? `You signed in with a passkey from another device or security key. Add one to ${deviceLabelForPrompt($passkeyUpgradePrompt.deviceName)} for faster access next time.`
                        : `Create a passkey for ${deviceLabelForPrompt($passkeyUpgradePrompt.deviceName)}. Sign in with your fingerprint, face, or device PIN while keeping your password as a backup.`}
                </p>
            </div>
            <div class="passkey-prompt__actions">
                <button
                    class="passkey-prompt__button passkey-prompt__button--secondary"
                    type="button"
                    onclick={dismiss}
                >
                    Not now
                </button>
                <button
                    bind:this={primaryButtonElement}
                    class="passkey-prompt__button passkey-prompt__button--primary"
                    type="button"
                    use:focusOnMount
                    onclick={startSetup}
                >
                    <KeyRound size={17} />
                    Create passkey
                </button>
            </div>
        </div>
    </div>
{/if}

<style>
    .passkey-prompt {
        position: fixed;
        z-index: 500;
        inset: 0;
        display: grid;
        place-items: center;
        padding: 24px;
    }

    .passkey-prompt__backdrop {
        position: absolute;
        inset: 0;
        width: 100%;
        height: 100%;
        border: 0;
        background: rgba(0, 0, 0, 0.72);
        cursor: default;
    }

    .passkey-prompt__dialog {
        position: relative;
        width: min(430px, 100%);
        display: flex;
        flex-direction: column;
        gap: 20px;
        padding: 24px;
        border: 1px solid var(--border-strong);
        border-radius: 8px;
        background: var(--bg-elevated);
        box-shadow: 0 24px 70px rgba(0, 0, 0, 0.48);
    }

    .passkey-prompt__close {
        position: absolute;
        top: 14px;
        right: 14px;
        width: 34px;
        height: 34px;
        display: grid;
        place-items: center;
        border: 0;
        border-radius: 6px;
        color: var(--text-muted);
        background: transparent;
    }

    .passkey-prompt__close:hover {
        color: var(--text-primary);
        background: var(--bg-hover);
    }

    .passkey-prompt__icon {
        width: 46px;
        height: 46px;
        display: grid;
        place-items: center;
        border: 1px solid var(--border-strong);
        border-radius: 8px;
        color: var(--text-secondary);
        background: var(--bg-hover);
    }

    .passkey-prompt__copy {
        display: flex;
        flex-direction: column;
        gap: 8px;
        padding-right: 24px;
    }

    .passkey-prompt__eyebrow {
        color: var(--text-muted);
        font-size: 11px;
        font-weight: 700;
        text-transform: uppercase;
    }

    .passkey-prompt__copy h2 {
        margin: 0;
        color: var(--text-primary);
        font-size: 24px;
        line-height: 1.2;
    }

    .passkey-prompt__copy p {
        margin: 0;
        color: var(--text-muted);
        font-size: 14px;
        line-height: 1.5;
    }

    .passkey-prompt__actions {
        display: flex;
        justify-content: flex-end;
        gap: 10px;
    }

    .passkey-prompt__button {
        min-height: 40px;
        display: inline-flex;
        align-items: center;
        justify-content: center;
        gap: 8px;
        padding: 9px 15px;
        border: 1px solid transparent;
        border-radius: 6px;
        font-size: 13px;
        font-weight: 650;
    }

    .passkey-prompt__button--secondary {
        border-color: var(--border-strong);
        color: var(--text-secondary);
        background: transparent;
    }

    .passkey-prompt__button--secondary:hover {
        color: var(--text-primary);
        background: var(--bg-hover);
    }

    .passkey-prompt__button--primary {
        border-color: var(--accent);
        color: var(--on-accent);
        background: var(--accent);
    }

    .passkey-prompt__button--primary:hover {
        filter: brightness(1.08);
    }
</style>

// apps/mobile/src/components/PasskeyUpgradePrompt.tsx
import React, { useEffect } from "react";
import { Modal, Pressable, StyleSheet, Text, View } from "react-native";

import {
    $hydrationStatus,
    $passkeyUpgradePrompt,
    vexService,
} from "@vex-chat/store";

import { Ionicons } from "@expo/vector-icons";
import { useStore } from "@nanostores/react";
import { useSafeAreaInsets } from "react-native-safe-area-context";

import { isPasskeySupported } from "../lib/passkey";
import { navigateToPasskeys } from "../navigation/navigationRef";
import { colors, fontFamilies, typography } from "../theme";

import { VexButton } from "./VexButton";

export function PasskeyUpgradePrompt() {
    const hydrationStatus = useStore($hydrationStatus);
    const prompt = useStore($passkeyUpgradePrompt);
    const safeArea = useSafeAreaInsets();
    const supported = isPasskeySupported();

    useEffect(() => {
        if (prompt && !supported) {
            vexService.dismissPasskeyUpgradePrompt();
        }
    }, [prompt, supported]);

    if (!prompt || !hydrationStatus.ready || !supported) {
        return null;
    }

    const fromAnotherAuthenticator = prompt.reason === "cross_platform_passkey";
    const suggestedName = passkeyNameForDevice(prompt.deviceName);
    const deviceLabel = deviceLabelForPrompt(prompt.deviceName);
    const dismiss = (): void => {
        vexService.dismissPasskeyUpgradePrompt();
    };
    const continueSetup = (): void => {
        const navigated = navigateToPasskeys({
            reason: prompt.reason,
            startSetup: true,
            suggestedName,
        });
        if (navigated) {
            dismiss();
        }
    };

    return (
        <Modal
            animationType="fade"
            onRequestClose={dismiss}
            presentationStyle="overFullScreen"
            statusBarTranslucent
            transparent
            visible
        >
            <Pressable
                onPress={dismiss}
                style={[
                    styles.backdrop,
                    { paddingBottom: Math.max(safeArea.bottom, 12) },
                ]}
            >
                <Pressable
                    accessibilityViewIsModal
                    onPress={(event) => {
                        event.stopPropagation();
                    }}
                    style={styles.sheet}
                >
                    <View style={styles.iconWrap}>
                        <Ionicons
                            color={colors.textSecondary}
                            name="key-outline"
                            size={24}
                        />
                    </View>
                    <View style={styles.copy}>
                        <Text style={styles.eyebrow}>FASTER SIGN-IN</Text>
                        <Text style={styles.title}>
                            {fromAnotherAuthenticator
                                ? "Add a passkey to this device"
                                : "Skip your password next time"}
                        </Text>
                        <Text style={styles.body}>
                            {fromAnotherAuthenticator
                                ? `You signed in with a passkey from another device or security key. Add one to ${deviceLabel} for faster access next time.`
                                : `Create a passkey for ${deviceLabel}. Sign in with your face, fingerprint, or device PIN while keeping your password as a backup.`}
                        </Text>
                    </View>
                    <View style={styles.actions}>
                        <VexButton
                            icon="key-outline"
                            onPress={continueSetup}
                            title="Create passkey"
                        />
                        <VexButton
                            onPress={dismiss}
                            title="Not now"
                            variant="outline"
                        />
                    </View>
                </Pressable>
            </Pressable>
        </Modal>
    );
}

function deviceLabelForPrompt(deviceName: string): string {
    const normalized = deviceName.trim().toLowerCase();
    if (normalized === "ios") return "this iPhone";
    if (normalized === "android") return "this Android device";
    return deviceName.trim() || "this device";
}

function passkeyNameForDevice(deviceName: string): string {
    const normalized = deviceName.trim().toLowerCase();
    if (normalized === "ios") return "iPhone";
    if (normalized === "android") return "Android phone";
    return deviceName.trim() || "This device";
}

const styles = StyleSheet.create({
    actions: {
        gap: 10,
    },
    backdrop: {
        backgroundColor: colors.overlay,
        flex: 1,
        justifyContent: "flex-end",
        padding: 12,
    },
    body: {
        ...typography.body,
        color: colors.muted,
    },
    copy: {
        gap: 8,
    },
    eyebrow: {
        ...typography.label,
        color: colors.mutedDark,
    },
    iconWrap: {
        alignItems: "center",
        backgroundColor: colors.elevated,
        borderColor: colors.border,
        borderRadius: 8,
        borderWidth: 1,
        height: 46,
        justifyContent: "center",
        width: 46,
    },
    sheet: {
        backgroundColor: colors.card,
        borderColor: colors.border,
        borderRadius: 8,
        borderWidth: 1,
        gap: 20,
        padding: 20,
    },
    title: {
        color: colors.text,
        fontFamily: fontFamilies.heading,
        fontSize: 24,
        fontWeight: "700",
        letterSpacing: 0,
        lineHeight: 29,
    },
});
